version: 2
jobs:
  build:
    docker:
      - image: crystallang/crystal:nightly
    steps:
      - checkout
      - run: shards install
          
  test:
    docker:
      - image: crystallang/crystal:nightly
    steps:
      - checkout
      - run: crystal spec
          