version: 2
jobs:
  build:
    docker:
      - image: crystallang/crystal:nightly
    steps:
      - checkout
      - run: shards install
      - run:
          name: run tests
          command: |
            mkdir tmp/test-results
            crystal spec -s -p -t --no-color > tmp/test-results/spec.out

      # collect reports
      - store_test_results:
          path: tmp/test-results
      - store_test_results:
          path: test-results

      - store_artifacts:
          path: tmp/test-results
          destination: test-results

          
  # test:
  #   docker:
  #     - image: crystallang/crystal:nightly
  #   steps:
  #     - checkout
  #     # - run: crystal spec