version: 2
jobs:
  build:
    docker:
      - image: crystallang/crystal:nightly
    steps:
      - checkout
      - run: shards install
          
  test:
    docker:
      - image: crystallang/crystal:nightly
    steps:
      - checkout
      # - run: crystal spec
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            crystal spec -s -p -t --junit_output /tmp/test-results/spec.txt

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results