version: 2
jobs:
  build:
    docker:
      - image: crystallang/crystal:nightly
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: 'crystal deps'
      - run:
          name: Run tests
          command: 'crystal spec'
          