version: 2
jobs:
  build:
    docker:
      - image: crystallang/crystal:nightly
    steps:
      - checkout
      - run: shards install
      - run:
          name: run tests
          command: |
            mkdir -p test-results/spec
            crystal -v > test-results/crystal_version.txt
            crystal eval 'require "./src/ai4cr"; puts "Ai4cr version: #{Ai4cr::VERSION}"' > test-results/app_version.txt
            time crystal spec --release --no-debug --time --error-trace --no-color > test-results/spec/results.txt

      # collect reports
      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
          destination: test-results
